apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo
  namespace: webinar-demo
spec:
  parentRefs:
    - name: webinar-gateway
  hostnames:
    - "podinfo.10.8.49.61.sslip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: podinfo
          port: 9898
